colour = $FFFFFF;
model = make_cylinder(radius, length, step, colour);
z = 0;
real_x = 0;
real_y = 0;
real_z = 0;
height = 0;
growth = 0.5;
can_draw = false;

cull_halfangle = obj_MDP.fov+30;